[package]
description = "Parity Ethereum Keys Generator"
name = "ethkey"
version = "0.4.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
edit-distance = "2.0"
parity-crypto = { git = "https://github.com/paritytech/parity-common/", branch = "EthKeyCrypto", features = ["publickey"] }
parity-wordlist = "1.3"
